# Generated by Django 2.0.6 on 2018-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tombo', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=40)),
                ('especificacao', models.CharField(max_length=40)),
            ],
        ),
    ]
