# Generated by Django 2.0.6 on 2018-07-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0003_auto_20180629_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locais.Local')),
            ],
        ),
    ]
