# Generated by Django 2.0.6 on 2018-07-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_auto_20180629_0841'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salas',
            new_name='Sala',
        ),
    ]
