# Generated by Django 2.0.6 on 2018-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
            ],
        ),
    ]
