# Generated by Django 2.0.6 on 2018-06-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locais',
            new_name='Locail',
        ),
    ]
