# Generated by Django 2.0.6 on 2018-06-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_auto_20180629_0841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locail',
            new_name='Local',
        ),
    ]
