# Generated by Django 2.0.6 on 2018-07-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0002_auto_20180701_1015'),
        ('locais', '0003_auto_20180629_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locais.Local')),
                ('sala_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salas.Sala')),
            ],
        ),
    ]
